### ISSUE TITLE
Update to React 15.3.2

### ISSUE THREAD

**Issue by iswanj** [asbjornenge/react-datalist#17]

**Comment by dcousens** [comment]
Seems to work for me,  I'd say you could just bump the peerDependency and be done with it.

**Comment by asbjornenge** [comment]
Sounds like a plan to me :+1: @iswanj you have been invited as a collaborator, so feel free to do what @dcousens suggests :smile:

**Comment by asbjornenge** [comment]
@iswanj updated peerDependencies and released under v4.0.0 :+1: :tada:
