### ISSUE TITLE
onOptionSelected not getting called

### ISSUE THREAD

**Issue by lachness** [asbjornenge/react-datalist#21]
I have a react-datalist component shown below.  I have onOptionSelected to callback a function that would do some processing after a selection has been made.  But the function onSelected is never called.
thx
lach

  ReactDatalist
      list="items"
      options={options}
      onOptionSelected={this.onSelected}
       />

**Comment by dcousens** [comment]
Is `this.onSelected` a function? (check to ensure no spelling errors)
